### ISSUE TITLE
How to connect from C# with Json/Rest

### ISSUE THREAD

**Issue by akeilox** [industrydive/dive-email-inliner#1]
I have tried to use Premailer.NET to inlnie Zurb-Ink but the inlining is very different than zurb's inliner and didnt work out. I found your implementation is very close or identical output like Zurb's inliner.

I am not familiar with Heroku but managed to deploy your implementation to mytesturl.heroku.com

I would like to be able to submit the HTML from a C# code to and get the inlined html back, via GET/POST, JSON or other means.

My question is, is there a mechanism for this already or do I need to edit the code? I dont know how i can edit the code within heroku (like giving the outhtml textarea a name, which is what i thought would be the easiest to get the inlined html via name/id).

Would appreciate your advise.

**Comment by elidickinson** [comment]
This project is just a thin wrapper around https://github.com/peterbe/premailer. It doesn't have a REST API, but it shouldn't be too hard to add one.

That said, you might want to take a look at http://premailer.io which uses the same backend library and is also open source. I think it might already have an API endpoint built.

**Comment by elidickinson** [comment]
I'm going to close this ticket, but reopen it if you have any additional questions

**Comment by akeilox** [comment]
Hi Eli
Thanks for the reply and pointing out premailer.io.

I have gone the simple route and slightly modified the form.html in your implementation.
I then do a POST to the /inliner page and read output. Dont know if there is a better way, but this works with C#, ajax etc.

Thank you again for sharing this, its the most complete Zurb Ink Inliner.

```
{% if outhtml %}
{{outhtml}}
{% elif inhtml %}
<html>
<body>
<form method=POST action="/inliner">
    <textarea name="inhtml" rows=12 cols=80>{{inhtml}}</textarea>
    <input type=submit name=submit value=submit>
</form>
</body>
</html>
{% endif %}
```
